title: Structured Software Jargon
description: My Personal Stack Problems
author: Dave McNavish
github: https://github.com/dmcnavish
about: I am a software developer that loves to search out new challenges and tackle them head on.
disqus_shortname: dmcnavish
google_analytics: UA-XXXXXXXX-Y
avatar_url: https://avatars1.githubusercontent.com/u/3458331?v=4&s=400

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
#    - icon: fa-facebook
#      link: "#"
#    - icon: fa-twitter
#      link: "https://twitter.com/dmcnavish"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/david-mcnavish-8a004722/"
    - icon: fa-stack-overflow
      link: "https://stackoverflow.com/users/947240/dmcnavish"
    - icon: fa-github
      link: "https://github.com/dmcnavish"

#share:
#  twitter_username: agusmakmun6
#  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: RSS
      url: /feed.xml
    - text: Tags
      url: /tags/

url: "https://dmcnavish.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
